// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutItem: typeof import('./components/items/aboutItem.vue')['default'];
    Addresses: typeof import('./components/items/carts/addresses.vue')['default'];
    AddressForm: typeof import('./components/items/carts/addressForm.vue')['default'];
    AddressPanel: typeof import('./components/items/carts/addressPanel.vue')['default'];
    Breadcrumb: typeof import('./components/navigation/breadcrumb.vue')['default'];
    CartBtn: typeof import('./components/navigation/CartBtn.vue')['default'];
    CartItem: typeof import('./components/items/carts/cartItem.vue')['default'];
    CartTable: typeof import('./components/items/carts/cartTable.vue')['default'];
    Categories: typeof import('./components/navigation/categories.vue')['default'];
    CategoryMenu: typeof import('./components/navigation/categoryMenu.vue')['default'];
    Crumbs: typeof import('./components/headers/crumbs.vue')['default'];
    DarkMode: typeof import('./components/navigation/darkMode.vue')['default'];
    DarkToggle: typeof import('./components/headers/darkToggle.vue')['default'];
    EmptyCart: typeof import('./components/items/carts/empty-cart.vue')['default'];
    FacebookButton: typeof import('./components/customer/facebookButton.vue')['default'];
    FavoriteItem: typeof import('./components/items/favoriteItem.vue')['default'];
    Footer: typeof import('./components/Footer.vue')['default'];
    Footers: typeof import('./components/layouts/footers.vue')['default'];
    HeaderMenu: typeof import('./components/headers/headerMenu.vue')['default'];
    ItemQty: typeof import('./components/items/itemQty.vue')['default'];
    LeftDrawer: typeof import('./components/layouts/leftDrawer.vue')['default'];
    Logos: typeof import('./components/Logos.vue')['default'];
    OptionColumn: typeof import('./components/items/optionColumn.vue')['default'];
    PageContainer: typeof import('./components/layouts/pageContainer.vue')['default'];
    PageHeader: typeof import('./components/layouts/pageHeader.vue')['default'];
    PaystackBtn: typeof import('./components/items/carts/paystackBtn.vue')['default'];
    ProductItem: typeof import('./components/items/productItem.vue')['default'];
    QBadge: typeof import('quasar')['QBadge'];
    QBtn: typeof import('quasar')['QBtn'];
    QBtnDropdown: typeof import('quasar')['QBtnDropdown'];
    QCard: typeof import('quasar')['QCard'];
    QCardActions: typeof import('quasar')['QCardActions'];
    QCardSection: typeof import('quasar')['QCardSection'];
    QCarousel: typeof import('quasar')['QCarousel'];
    QCarouselSlide: typeof import('quasar')['QCarouselSlide'];
    QDialog: typeof import('quasar')['QDialog'];
    QDrawer: typeof import('quasar')['QDrawer'];
    QExpansionItem: typeof import('quasar')['QExpansionItem'];
    QFooter: typeof import('quasar')['QFooter'];
    QHeader: typeof import('quasar')['QHeader'];
    QIcon: typeof import('quasar')['QIcon'];
    QImg: typeof import('quasar')['QImg'];
    QItem: typeof import('quasar')['QItem'];
    QItemLabel: typeof import('quasar')['QItemLabel'];
    QItemSection: typeof import('quasar')['QItemSection'];
    QLayout: typeof import('quasar')['QLayout'];
    QList: typeof import('quasar')['QList'];
    QPage: typeof import('quasar')['QPage'];
    QPageContainer: typeof import('quasar')['QPageContainer'];
    QScrollArea: typeof import('quasar')['QScrollArea'];
    QSpace: typeof import('quasar')['QSpace'];
    QToolbar: typeof import('quasar')['QToolbar'];
    QToolbarTitle: typeof import('quasar')['QToolbarTitle'];
    RateItem: typeof import('./components/items/rateItem.vue')['default'];
    RegisterBasic: typeof import('./components/customer/registration/registerBasic.vue')['default'];
    RegisterDelivery: typeof import('./components/customer/registration/registerDelivery.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SeachComponent: typeof import('./components/headers/seachComponent.vue')['default'];
    SearchMenu: typeof import('./components/headers/search-menu.vue')['default'];
    SideMenuItem: typeof import('./components/layouts/sideMenuItem.vue')['default'];
    ToolbarHeader: typeof import('./components/headers/toolbarHeader.vue')['default'];
    ViewedItems: typeof import('./components/items/viewedItems.vue')['default'];
    VitalWelcome: typeof import('./components/VitalWelcome.vue')['default'];
  }
}

export {};
